<?php

namespace App\Models;

use App\RecordsActivity;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    use HasFactory,RecordsActivity;
    protected $guarded;
    public static $recordableEvents=['created'];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

    public function path()
    {
        return '/plans/'.$this->id;
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }

    public function activities()
    {
        return $this->morphMany(Activity::class,'activitable');
    }


}
